# Generated by Django 5.2 on 2025-04-03 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='ecommerces.order'),
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='ecommerces.product'),
        ),
    ]
