# Generated by Django 5.2 on 2025-04-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0002_discount_amount_discount_order_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ecommerces.cart'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerces.product'),
        ),
    ]
