# Generated by Django 5.2 on 2025-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0003_alter_cartdetail_cart_alter_cartdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
