# Generated by Django 5.2 on 2025-04-14 08:07

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0010_remove_order_payment_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='ecommerces.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
