# Generated by Django 5.2 on 2025-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0012_alter_orderdetail_order_alter_orderdetail_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'Paypal'), ('COD', 'Thanh toán khi nhận hàng'), ('BANK', 'Chuyển khoản ngân hàng')], default='COD', max_length=50),
        ),
    ]
