# Generated by Django 5.2 on 2025-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0014_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('PAID', 'Đã thanh toán'), ('SHIPPING', 'Đang giao'), ('COMPLETED', 'Đã giao'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
    ]
