# Generated by Django 5.2 on 2025-05-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0018_alter_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
