# Generated by Django 5.2 on 2025-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0020_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PAYPAL', 'Paypal'), ('COD', 'Thanh toán khi nhận hàng')], default='COD', max_length=50),
        ),
    ]
