# Generated by Django 5.2 on 2025-08-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0024_remove_inventory_product_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ecommerces.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
