# Generated by Django 5.2 on 2025-08-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0025_remove_product_inventory_inventory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='color',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
