# Generated by Django 5.2 on 2025-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0026_inventory_color_alter_inventory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='sku',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.CharField(default='', max_length=100),
        ),
    ]
