# Generated by Django 5.2 on 2025-08-16 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0027_cartdetail_sku_inventory_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderdetail',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='ecommerces.inventory'),
        ),
    ]
