# Generated by Django 5.2 on 2025-08-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0028_shoporderdetail_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='sku',
            new_name='color',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
