# Generated by Django 5.2 on 2025-08-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0029_rename_sku_cartdetail_color_cartdetail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='ecommerces.order'),
        ),
    ]
