# Generated by Django 5.2 on 2025-08-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0030_alter_shoporder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporderdetail',
            name='shop_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ecommerces.shoporder'),
        ),
    ]
